version: "3.9"
services:
  db:
    container_name: postgresDB
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  web:
    container_name: bakalarka
    build: .
    volumes:
      - .:/code/
    environment:
      - DJANGO_SUPERUSER_PASSWORD=159admin159
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=david.korman1@gmail.com
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py createsuperuser --no-input
        python3 manage.py loaddata data
        python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db