# Generated by Django 3.1.6 on 2021-02-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Zena'), ('M', 'Muz'), ('O', 'Ine')], default='M', max_length=1),
        ),
    ]
