# Generated by Django 3.1.6 on 2021-02-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210223_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPrisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prisoner')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
