# Generated by Django 3.1.6 on 2021-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
