# Generated by Django 3.1.6 on 2021-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='department',
            field=models.IntegerField(),
        ),
    ]
