# Generated by Django 3.1.6 on 2021-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_grouppage_matchpages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
