# Generated by Django 3.1.6 on 2021-03-04 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('text', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('text', django_quill.fields.QuillField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.forumcategory')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grouppage',
            options={'verbose_name': 'Skupina stranok', 'verbose_name_plural': 'Skupiny stranok'},
        ),
        migrations.AlterModelOptions(
            name='matchpages',
            options={'verbose_name': 'Priradenie do skupin', 'verbose_name_plural': 'Priradenie stranok do skupin'},
        ),
        migrations.AlterModelOptions(
            name='matchprisoner',
            options={'verbose_name': 'Priradenie vazna', 'verbose_name_plural': 'Priradenie vaznov'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Stranka', 'verbose_name_plural': 'Stranky'},
        ),
        migrations.AlterModelOptions(
            name='prisoner',
            options={'verbose_name': 'Väzen', 'verbose_name_plural': 'Väzni'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Najcastesia otazka', 'verbose_name_plural': 'Najcastesie otazky'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Uzivatelia'},
        ),
        migrations.CreateModel(
            name='MatchForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.forumcomment')),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.forumpost')),
            ],
        ),
        migrations.AddField(
            model_name='forumpost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
