# Generated by Django 3.1.6 on 2021-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210304_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
