# Generated by Django 3.1.6 on 2021-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210306_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1024)),
                ('text', models.TextField()),
                ('image', models.TextField()),
            ],
            options={
                'verbose_name': 'Prezentačný slajd',
                'verbose_name_plural': 'Prezentačné slajdy',
            },
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name': 'Kategória fóra', 'verbose_name_plural': 'Kategórie fóra'},
        ),
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'verbose_name': 'Komentár k príspevku vo fóre', 'verbose_name_plural': 'Komentáre vo fóre'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'Otázka vo fóre', 'verbose_name_plural': 'Otázky fo fóre'},
        ),
        migrations.AlterModelOptions(
            name='matchforumcomment',
            options={'verbose_name': 'Priradenie komentáru k príspevku vo fóre', 'verbose_name_plural': 'Priradenie komentárov k príspevkom'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
