# Generated by Django 3.1.6 on 2021-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_news_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/uploaded/'),
        ),
    ]
