# Generated by Django 3.1.6 on 2021-03-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
    ]
