# Generated by Django 3.1.6 on 2021-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisoner',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='acc_adr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='acc_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='iban',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='department',
            name='lat',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='department',
            name='long',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='department',
            name='web',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
