# Generated by Django 3.1.6 on 2021-04-05 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210404_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
