# Generated by Django 3.1.6 on 2021-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210405_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
