# Generated by Django 3.1.6 on 2021-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_requests_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='answer',
            field=models.TextField(blank=True, help_text='Odpoveď'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(help_text='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='Upravené'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.TextField(help_text='Odôvodnenie'),
        ),
    ]
