# Generated by Django 3.1.6 on 2021-05-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210407_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='ustav'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Odpoveď'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Upravené'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='prisoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prisoner', verbose_name='Väzeň'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.TextField(verbose_name='Odôvodnenie'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='state',
            field=models.CharField(choices=[('R', 'Rieši sa'), ('S', 'Schválená'), ('F', 'Zamietnutá'), ('P', 'Poslaná')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='type',
            field=models.CharField(choices=[('N', 'Žiadosť o návštevu'), ('T', 'Žiadosť o telefonát'), ('V', 'Žiadosť o videohovor')], default='N', max_length=1, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
    ]
