# Generated by Django 3.1.6 on 2021-05-12 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210511_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Odôvodnenie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('answer', models.TextField(blank=True, verbose_name='Odpoveď')),
                ('state', models.CharField(choices=[('R', 'Rieši sa'), ('S', 'Schválená'), ('F', 'Zamietnutá'), ('P', 'Poslaná')], default='P', max_length=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name_plural': 'Žiadosti o pridelenie informácií o väzňovi',
            },
        ),
    ]
